// Generated by CoffeeScript 1.3.2
(function() {
  var alt_pressed_at, qrcode_url, showing_qrcode;

  showing_qrcode = false;

  alt_pressed_at = 0;

  qrcode_url = function(data, width, height) {
    if (width == null) {
      width = 150;
    }
    if (height == null) {
      height = 150;
    }
    return "https://chart.googleapis.com/chart?chs=" + (parseInt(width, 10)) + "x" + (parseInt(height, 10)) + "&cht=qr&chl=" + (encodeURIComponent(data));
  };

  $(document).on('keyup', '*', function(event) {
    if (event.keyIdentifier === "Alt") {
      return alt_pressed_at = event.timeStamp;
    }
  });

  $(document).on('keydown', '*', function(event) {
    if (event.keyIdentifier === "Alt" && event.timeStamp - alt_pressed_at <= 500) {
      return console.log(qrcode_url(window.location.href));
    }
  });

}).call(this);
